import type { Customer } from "../types/customer";

export const customers: Customer[] = [
  {
    id: "1",
    customerNo: "CUS001",
    name: "Rahul Das",
    mobile: "9876543210",
    email: "rahul@gmail.com",
    address: "Haldia",
    gstNo: "",
    openingBalance: 0,
    balance: 1200,
    type: "CUSTOMER",
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "2",
    customerNo: "CUS002",
    name: "Suman Roy",
    mobile: "9007008000",
    email: "suman@gmail.com",
    address: "Kolkata",
    gstNo: "",
    openingBalance: 0,
    balance: 0,
    type: "CUSTOMER",
    isActive: true,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "3",
    customerNo: "CUS003",
    name: "Amit Paul",
    mobile: "8912345678",
    email: "",
    address: "Durgapur",
    gstNo: "",
    openingBalance: 0,
    balance: 550,
    type: "CUSTOMER",
    isActive: false,
    createdAt: "",
    updatedAt: "",
  },
];
