export interface InvoiceCompany {
  name: string;

  address: string;

  phone: string;

  email?: string;

  gstNo?: string;

  logo?: string;
}

export interface InvoiceCustomer {
  name: string;

  mobile?: string;

  address?: string;

  gstNo?: string;
}

export interface InvoiceItem {
  productCode: string;

  productName: string;

  hsnCode?: string;

  quantity: number;

  unit: string;

  rate: number;

  tax: number;

  total: number;
}

export interface InvoiceData {
  invoiceNo: string;

  saleNo: string;

  saleDate: Date;

  company: InvoiceCompany;

  customer?: InvoiceCustomer;

  items: InvoiceItem[];

  subtotal: number;

  discount: number;

  taxAmount: number;

  grandTotal: number;

  paidAmount: number;

  dueAmount: number;

  paymentMethod: string;

  notes?: string;
}

export function generateInvoiceTemplate(invoice: InvoiceData): string {
  const itemRows = invoice.items
    .map(
      (item, index) => `
      <tr>
        <td>${index + 1}</td>
        <td>${item.productCode}</td>
        <td>${item.productName}</td>
        <td>${item.hsnCode ?? ""}</td>
        <td>${item.quantity}</td>
        <td>${item.unit}</td>
        <td>₹${item.rate.toFixed(2)}</td>
        <td>${item.tax}%</td>
        <td>₹${item.total.toFixed(2)}</td>
      </tr>
    `,
    )
    .join("");

  return `
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8"/>

<title>Invoice</title>

<style>

body{
font-family:Arial,sans-serif;
padding:30px;
font-size:13px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:15px;
}

th,
td{
border:1px solid #ddd;
padding:8px;
}

th{
background:#f3f3f3;
}

.header{
display:flex;
justify-content:space-between;
margin-bottom:20px;
}

.right{
text-align:right;
}

.total{
margin-top:20px;
width:300px;
margin-left:auto;
}

.total td{
border:none;
}

.footer{
margin-top:40px;
font-size:12px;
text-align:center;
color:#777;
}

</style>

</head>

<body>

<div class="header">

<div>

<h2>${invoice.company.name}</h2>

<div>${invoice.company.address}</div>

<div>${invoice.company.phone}</div>

<div>${invoice.company.email ?? ""}</div>

<div>GST : ${invoice.company.gstNo ?? "-"}</div>

</div>

<div class="right">

<h2>TAX INVOICE</h2>

<div>Invoice : ${invoice.invoiceNo}</div>

<div>Sale : ${invoice.saleNo}</div>

<div>Date : ${invoice.saleDate.toLocaleDateString()}</div>

</div>

</div>

<hr/>

<h3>Bill To</h3>

<div>${invoice.customer?.name ?? "Walk-in Customer"}</div>

<div>${invoice.customer?.mobile ?? ""}</div>

<div>${invoice.customer?.address ?? ""}</div>

<div>${invoice.customer?.gstNo ?? ""}</div>

<table>

<thead>

<tr>

<th>#</th>

<th>Code</th>

<th>Product</th>

<th>HSN</th>

<th>Qty</th>

<th>Unit</th>

<th>Rate</th>

<th>GST</th>

<th>Total</th>

</tr>

</thead>

<tbody>

${itemRows}

</tbody>

</table>

<table class="total">

<tr>

<td>Subtotal</td>

<td>₹${invoice.subtotal.toFixed(2)}</td>

</tr>

<tr>

<td>Discount</td>

<td>₹${invoice.discount.toFixed(2)}</td>

</tr>

<tr>

<td>Tax</td>

<td>₹${invoice.taxAmount.toFixed(2)}</td>

</tr>

<tr>

<td><strong>Grand Total</strong></td>

<td><strong>₹${invoice.grandTotal.toFixed(2)}</strong></td>

</tr>

<tr>

<td>Paid</td>

<td>₹${invoice.paidAmount.toFixed(2)}</td>

</tr>

<tr>

<td>Due</td>

<td>₹${invoice.dueAmount.toFixed(2)}</td>

</tr>

<tr>

<td>Payment</td>

<td>${invoice.paymentMethod}</td>

</tr>

</table>

<div class="footer">

${invoice.notes ?? ""}

<br/><br/>

Generated by Firecracker ERP

</div>

</body>

</html>
`;
}
