import { Request, Response } from "express";
import SettingsRepository from "../../settings/repositories/settings.repository.js";
import ReportService, {
  type ReportBusinessContext,
  type ReportGeneratedBy,
} from "../services/report.service.js";

import { sendPdf } from "../helpers/report-response.js";

class ReportController {
  /* ======================================================================== */
  /* DATE RANGE                                                               */
  /* ======================================================================== */

  private getDates(req: Request) {
    const from = req.query.from
      ? new Date(String(req.query.from))
      : new Date("2000-01-01");

    const to = req.query.to ? new Date(String(req.query.to)) : new Date();

    if (Number.isNaN(from.getTime())) {
      throw new Error("Invalid report start date.");
    }

    if (Number.isNaN(to.getTime())) {
      throw new Error("Invalid report end date.");
    }

    if (from > to) {
      throw new Error("Report start date cannot be after end date.");
    }

    return { from, to };
  }

  /* ======================================================================== */
  /* BUSINESS CONTEXT                                                         */
  /* ======================================================================== */

  private async getBusinessContext(
    _req: Request,
  ): Promise<ReportBusinessContext> {
    const settings = await SettingsRepository.find();

    if (!settings) {
      throw new Error(
        "Business settings not found. Please complete your business setup first.",
      );
    }

    const business = settings.business;
    const businessId = settings.users.businessId;

    if (!business?.name) {
      throw new Error(
        "Business name is not configured. Please update business settings.",
      );
    }

    if (!businessId) {
      throw new Error(
        "Business ID is not configured. Please update business settings.",
      );
    }

    return {
      name: business.name,
      businessId,
      ownerName: business.ownerName,
      address: business.address ?? "",
      phone: business.phone ?? "",
      email: business.email,
      website: business.website,
      gstNo: business.gstNo,
      logo: business.logo,
    };
  }

  /* ======================================================================== */
  /* GENERATED BY                                                             */
  /* ======================================================================== */

  private getGeneratedBy(req: Request): ReportGeneratedBy {
    return {
      userId: req.user?.userId,
      name: (req.user as { name?: string } | undefined)?.name,
    };
  }

  /* ======================================================================== */
  /* JSON REPORTS                                                             */
  /* ======================================================================== */

  sales = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.salesData(from, to);

    return res.status(200).json({
      success: true,
      message: "Sales report fetched successfully.",
      data,
    });
  };

  purchase = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.purchaseData(from, to);

    return res.status(200).json({
      success: true,
      message: "Purchase report fetched successfully.",
      data,
    });
  };

  customer = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.customerData(from, to);

    return res.status(200).json({
      success: true,
      message: "Customer report fetched successfully.",
      data,
    });
  };

  supplier = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.supplierData(from, to);

    return res.status(200).json({
      success: true,
      message: "Supplier report fetched successfully.",
      data,
    });
  };

  stock = async (_req: Request, res: Response) => {
    const data = await ReportService.stockData();

    return res.status(200).json({
      success: true,
      message: "Stock report fetched successfully.",
      data,
    });
  };

  profitLoss = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.profitData(from, to);

    return res.status(200).json({
      success: true,
      message: "Profit report fetched successfully.",
      data,
    });
  };

  /* ======================================================================== */
  /* OVERVIEW                                                                 */
  /* ======================================================================== */

  overview = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const data = await ReportService.summary(from, to);

    return res.status(200).json({
      success: true,
      message: "Reports overview fetched successfully.",
      data,
    });
  };

  /* ======================================================================== */
  /* PDF REPORTS                                                              */
  /* ======================================================================== */

  salesPdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.salesReport(
      from,
      to,
      business,
      generatedBy,
    );

    return sendPdf(res, pdf, "sales-report.pdf");
  };

  purchasePdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.purchaseReport(
      from,
      to,
      business,
      generatedBy,
    );

    return sendPdf(res, pdf, "purchase-report.pdf");
  };

  customerPdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.customerReport(
      from,
      to,
      business,
      generatedBy,
    );

    return sendPdf(res, pdf, "customer-report.pdf");
  };

  supplierPdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.supplierReport(
      from,
      to,
      business,
      generatedBy,
    );

    return sendPdf(res, pdf, "supplier-report.pdf");
  };

  stockPdf = async (req: Request, res: Response) => {
    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.stockReport(business, generatedBy);

    return sendPdf(res, pdf, "stock-report.pdf");
  };

  lowStockPdf = async (req: Request, res: Response) => {
    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.lowStockReport(business, generatedBy);

    return sendPdf(res, pdf, "low-stock-report.pdf");
  };

  gstPdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.gstReport(from, to, business, generatedBy);

    return sendPdf(res, pdf, "gst-report.pdf");
  };

  profitLossPdf = async (req: Request, res: Response) => {
    const { from, to } = this.getDates(req);

    const business = await this.getBusinessContext(req);
    const generatedBy = this.getGeneratedBy(req);

    const pdf = await ReportService.profitLossReport(
      from,
      to,
      business,
      generatedBy,
    );

    return sendPdf(res, pdf, "profit-loss-report.pdf");
  };
}

export default new ReportController();
