import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface CustomerReportRow {
  name: string;

  mobile: string;

  totalInvoices: number;

  totalSales: number;

  totalDue: number;
}

interface CustomerReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  rows: CustomerReportRow[];
}

export async function generateCustomerReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: CustomerReportOptions): Promise<Buffer> {
  const totalSales = rows.reduce((sum, item) => sum + item.totalSales, 0);

  const totalDue = rows.reduce((sum, item) => sum + item.totalDue, 0);

  const options: PdfOptions = {
    title: "Customer Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Customer",
        key: "name",
        width: 160,
      },
      {
        title: "Mobile",
        key: "mobile",
        width: 120,
      },
      {
        title: "Invoices",
        key: "totalInvoices",
        width: 70,
        align: "right",
      },
      {
        title: "Sales",
        key: "totalSales",
        width: 90,
        align: "right",
      },
      {
        title: "Due",
        key: "totalDue",
        width: 90,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      name: item.name,

      mobile: item.mobile,

      totalInvoices: item.totalInvoices,

      totalSales: `₹${item.totalSales.toFixed(2)}`,

      totalDue: `₹${item.totalDue.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",
        value: generatedBy,
      },
      {
        label: "Date Range",
        value: dateRange,
      },
      {
        label: "Customers",
        value: rows.length,
      },
      {
        label: "Total Sales",
        value: `₹${totalSales.toFixed(2)}`,
      },
      {
        label: "Outstanding Due",
        value: `₹${totalDue.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
