// import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

// interface ExpenseReportRow {
//   expenseNo: string;

//   category: string;

//   date: string;

//   amount: number;
// }

// interface ExpenseReportOptions {
//   businessName: string;

//   generatedBy: string;

//   dateRange: string;

//   rows: ExpenseReportRow[];
// }

// export async function generateExpenseReport({
//   businessName,
//   generatedBy,
//   dateRange,
//   rows,
// }: ExpenseReportOptions): Promise<Buffer> {
//   const totalExpense = rows.reduce((sum, item) => sum + item.amount, 0);

//   const options: PdfOptions = {
//     title: "Expense Report",

//     company: {
//       name: businessName,

//       address: "",

//       phone: "",
//     },

//     columns: [
//       {
//         title: "Expense No",
//         key: "expenseNo",
//         width: 120,
//       },
//       {
//         title: "Category",
//         key: "category",
//         width: 180,
//       },
//       {
//         title: "Date",
//         key: "date",
//         width: 90,
//       },
//       {
//         title: "Amount",
//         key: "amount",
//         width: 100,
//         align: "right",
//       },
//     ],

//     rows: rows.map((item) => ({
//       expenseNo: item.expenseNo,

//       category: item.category,

//       date: item.date,

//       amount: `₹${item.amount.toFixed(2)}`,
//     })),

//     summary: [
//       {
//         label: "Generated By",

//         value: generatedBy,
//       },
//       {
//         label: "Date Range",

//         value: dateRange,
//       },
//       {
//         label: "Total Expenses",

//         value: rows.length,
//       },
//       {
//         label: "Expense Amount",

//         value: `₹${totalExpense.toFixed(2)}`,
//       },
//     ],
//   };

//   return PdfService.generate(options);
// }
