import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface GSTReportRow {
  taxRate: number;

  taxableAmount: number;

  gstAmount: number;
}

interface GSTReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  rows: GSTReportRow[];
}

export async function generateGSTReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: GSTReportOptions): Promise<Buffer> {
  const taxable = rows.reduce((sum, item) => sum + item.taxableAmount, 0);

  const gst = rows.reduce((sum, item) => sum + item.gstAmount, 0);

  const options: PdfOptions = {
    title: "GST Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "GST %",
        key: "taxRate",
        width: 100,
      },
      {
        title: "Taxable Amount",
        key: "taxableAmount",
        width: 180,
        align: "right",
      },
      {
        title: "GST Amount",
        key: "gstAmount",
        width: 180,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      taxRate: `${item.taxRate}%`,

      taxableAmount: `₹${item.taxableAmount.toFixed(2)}`,

      gstAmount: `₹${item.gstAmount.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",

        value: generatedBy,
      },
      {
        label: "Date Range",

        value: dateRange,
      },
      {
        label: "Taxable Amount",

        value: `₹${taxable.toFixed(2)}`,
      },
      {
        label: "GST Amount",

        value: `₹${gst.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
