import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface LowStockReportRow {
  productCode: string;

  productName: string;

  category: string;

  stock: number;

  minimumStock: number;
}

interface LowStockReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  rows: LowStockReportRow[];
}

export async function generateLowStockReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: LowStockReportOptions): Promise<Buffer> {
  const options: PdfOptions = {
    title: "Low Stock Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Code",
        key: "productCode",
        width: 90,
      },
      {
        title: "Product",
        key: "productName",
        width: 180,
      },
      {
        title: "Category",
        key: "category",
        width: 120,
      },
      {
        title: "Stock",
        key: "stock",
        width: 70,
        align: "right",
      },
      {
        title: "Minimum",
        key: "minimumStock",
        width: 80,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      productCode: item.productCode,

      productName: item.productName,

      category: item.category,

      stock: item.stock,

      minimumStock: item.minimumStock,
    })),

    summary: [
      {
        label: "Generated By",
        value: generatedBy,
      },
      {
        label: "Date Range",
        value: dateRange,
      },
      {
        label: "Low Stock Items",
        value: rows.length,
      },
    ],
  };

  return PdfService.generate(options);
}
