import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface ProfitLossReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  sales: number;

  purchase: number;

  expense: number;

  purchaseCost: number;

  grossProfit: number;

  netProfit: number;
}

export async function generateProfitLossReport({
  businessName,
  generatedBy,
  dateRange,
  sales,
  purchase,
  expense,
  purchaseCost,
  grossProfit,
  netProfit,
}: ProfitLossReportOptions): Promise<Buffer> {
  const options: PdfOptions = {
    title: "Profit & Loss Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [],

    rows: [],

    summary: [
      {
        label: "Generated By",

        value: generatedBy,
      },
      {
        label: "Date Range",

        value: dateRange,
      },
      {
        label: "Sales",

        value: `₹${sales.toFixed(2)}`,
      },
      {
        label: "Purchase",

        value: `₹${purchase.toFixed(2)}`,
      },
      {
        label: "Purchase Cost",

        value: `₹${purchaseCost.toFixed(2)}`,
      },
      {
        label: "Expenses",

        value: `₹${expense.toFixed(2)}`,
      },
      {
        label: "Gross Profit",

        value: `₹${grossProfit.toFixed(2)}`,
      },
      {
        label: "Net Profit",

        value: `₹${netProfit.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
