import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface PurchaseReportRow {
  purchaseNo: string;

  supplier: string;

  date: string;

  total: number;
}

interface PurchaseReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  rows: PurchaseReportRow[];
}

export async function generatePurchaseReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: PurchaseReportOptions): Promise<Buffer> {
  const totalPurchase = rows.reduce((sum, item) => sum + item.total, 0);

  const options: PdfOptions = {
    title: "Purchase Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Purchase No",
        key: "purchaseNo",
        width: 120,
      },
      {
        title: "Supplier",
        key: "supplier",
        width: 180,
      },
      {
        title: "Date",
        key: "date",
        width: 90,
      },
      {
        title: "Amount",
        key: "total",
        width: 100,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      purchaseNo: item.purchaseNo,

      supplier: item.supplier,

      date: item.date,

      total: `₹${item.total.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",

        value: generatedBy,
      },
      {
        label: "Date Range",

        value: dateRange,
      },
      {
        label: "Total Purchases",

        value: rows.length,
      },
      {
        label: "Purchase Amount",

        value: `₹${totalPurchase.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
