import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface SalesReportRow {
  invoiceNo: string;
  customer: string;
  date: string;
  paymentMethod: string;
  total: number;
}

interface SalesReportOptions {
  businessName: string;
  generatedBy: string;
  dateRange: string;
  rows: SalesReportRow[];
}

export async function generateSalesReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: SalesReportOptions): Promise<Buffer> {
  const totalSales = rows.reduce((sum, item) => sum + item.total, 0);

  const options: PdfOptions = {
    title: "Sales Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Invoice",
        key: "invoiceNo",
        width: 80,
      },
      {
        title: "Customer",
        key: "customer",
        width: 160,
      },
      {
        title: "Date",
        key: "date",
        width: 90,
      },
      {
        title: "Payment",
        key: "paymentMethod",
        width: 90,
      },
      {
        title: "Amount",
        key: "total",
        width: 90,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      invoiceNo: item.invoiceNo,

      customer: item.customer,

      date: item.date,

      paymentMethod: item.paymentMethod,

      total: `₹${item.total.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",
        value: generatedBy,
      },
      {
        label: "Date Range",
        value: dateRange,
      },
      {
        label: "Total Invoices",
        value: rows.length,
      },
      {
        label: "Total Sales",
        value: `₹${totalSales.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
