import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface StockReportRow {
  productCode: string;

  productName: string;

  category: string;

  stock: number;

  value: number;
}

interface StockReportOptions {
  businessName: string;

  generatedBy: string;

  rows: StockReportRow[];
}

export async function generateStockReport({
  businessName,
  generatedBy,
  rows,
}: StockReportOptions): Promise<Buffer> {
  const stockValue = rows.reduce((sum, item) => sum + item.value, 0);

  const options: PdfOptions = {
    title: "Stock Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Code",
        key: "productCode",
        width: 80,
      },
      {
        title: "Product",
        key: "productName",
        width: 170,
      },
      {
        title: "Category",
        key: "category",
        width: 110,
      },
      {
        title: "Stock",
        key: "stock",
        width: 70,
        align: "right",
      },
      {
        title: "Value",
        key: "value",
        width: 90,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      productCode: item.productCode,

      productName: item.productName,

      category: item.category,

      stock: item.stock,

      value: `₹${item.value.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",

        value: generatedBy,
      },
      {
        label: "Products",

        value: rows.length,
      },
      {
        label: "Stock Value",

        value: `₹${stockValue.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
