import { PdfService, type PdfOptions } from "../../../common/pdf/index.js";

interface SupplierReportRow {
  name: string;

  mobile: string;

  totalPurchases: number;

  purchaseAmount: number;
}

interface SupplierReportOptions {
  businessName: string;

  generatedBy: string;

  dateRange: string;

  rows: SupplierReportRow[];
}

export async function generateSupplierReport({
  businessName,
  generatedBy,
  dateRange,
  rows,
}: SupplierReportOptions): Promise<Buffer> {
  const purchaseAmount = rows.reduce(
    (sum, item) => sum + item.purchaseAmount,
    0,
  );

  const options: PdfOptions = {
    title: "Supplier Report",

    company: {
      name: businessName,

      address: "",

      phone: "",
    },

    columns: [
      {
        title: "Supplier",
        key: "name",
        width: 180,
      },
      {
        title: "Mobile",
        key: "mobile",
        width: 120,
      },
      {
        title: "Purchases",
        key: "totalPurchases",
        width: 90,
        align: "right",
      },
      {
        title: "Amount",
        key: "purchaseAmount",
        width: 100,
        align: "right",
      },
    ],

    rows: rows.map((item) => ({
      name: item.name,

      mobile: item.mobile,

      totalPurchases: item.totalPurchases,

      purchaseAmount: `₹${item.purchaseAmount.toFixed(2)}`,
    })),

    summary: [
      {
        label: "Generated By",

        value: generatedBy,
      },
      {
        label: "Date Range",

        value: dateRange,
      },
      {
        label: "Suppliers",

        value: rows.length,
      },
      {
        label: "Purchase Amount",

        value: `₹${purchaseAmount.toFixed(2)}`,
      },
    ],
  };

  return PdfService.generate(options);
}
