import { PdfDocument } from "../types/pdf.types.js";

interface PdfFooterOptions {
  generatedBy?: string;
  finalPage?: boolean;
  pageNumber: number;
  totalPages: number;
}

export function drawPdfFooter(doc: PdfDocument, options: PdfFooterOptions) {
  const { generatedBy, finalPage, pageNumber, totalPages } = options;

  const margin = doc.page.margins.left;

  const pageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const bottom = doc.page.height - doc.page.margins.bottom;

  /* ------------------------------------------------------------------------ */
  /* FINAL PAGE FOOTER                                                        */
  /* ------------------------------------------------------------------------ */

  if (finalPage) {
    const signatureY = bottom - 70;

    /* Divider */

    doc
      .moveTo(margin, signatureY - 12)
      .lineTo(margin + pageWidth, signatureY - 12)
      .lineWidth(0.5)
      .strokeColor("#E2E8F0")
      .stroke();

    /* Thank you */

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#64748B")
      .text("Thank you for your business!", margin, signatureY, {
        width: pageWidth,
        align: "left",
      });

    /* Signature */

    const signatureWidth = 150;

    const signatureX = margin + pageWidth - signatureWidth;

    doc
      .moveTo(signatureX, signatureY + 25)
      .lineTo(signatureX + signatureWidth, signatureY + 25)
      .lineWidth(0.7)
      .strokeColor("#94A3B8")
      .stroke();

    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor("#64748B")
      .text("Authorized Signature", signatureX, signatureY + 30, {
        width: signatureWidth,
        align: "center",
      });
  }

  /* ------------------------------------------------------------------------ */
  /* SYSTEM FOOTER                                                            */
  /* ------------------------------------------------------------------------ */

  doc
    .font("Helvetica")
    .fontSize(7.5)
    .fillColor("#94A3B8")
    .text(
      `Generated by ${generatedBy || "OneHub ERP System"}`,
      margin,
      bottom - 10,
      {
        width: pageWidth / 2,
      },
    );

  /* ------------------------------------------------------------------------ */
  /* PAGE NUMBER                                                              */
  /* ------------------------------------------------------------------------ */

  doc
    .font("Helvetica")
    .fontSize(7.5)
    .fillColor("#94A3B8")
    .text(
      `Page ${pageNumber} of ${totalPages}`,
      margin + pageWidth / 2,
      bottom - 10,
      {
        width: pageWidth / 2,
        align: "right",
      },
    );

  doc.fillColor("#0F172A");
}
