import { PdfDocument } from "../types/pdf.types.js";

export function drawPdfFooter(doc: PdfDocument, notes?: string) {
  doc.moveDown(2);

  if (notes) {
    doc.font("Helvetica-Bold").fontSize(10).text("Notes");

    doc.font("Helvetica").fontSize(9).text(notes);

    doc.moveDown();
  }

  doc.font("Helvetica").fontSize(9).text("Thank you for your business!", {
    align: "center",
  });

  doc.moveDown(2);

  doc.text("Authorized Signature", {
    align: "right",
  });

  doc.moveDown();

  doc
    .fontSize(8)
    .fillColor("gray")
    .text("Generated by Firecracker Management System", {
      align: "center",
    });

  doc.fillColor("black");
}
