import { PurchaseOcrResult } from "../interfaces/purchase-ocr.interface.js";

export function buildPurchaseDraft(invoice: PurchaseOcrResult) {
  return {
    supplier: invoice.supplier.id ?? null,

    invoiceNo: invoice.invoiceNumber,

    purchaseDate: invoice.invoiceDate
      ? new Date(invoice.invoiceDate)
      : new Date(),

    items: invoice.items
      .filter((item) => item.matched)
      .map((item) => ({
        product: item.productId,

        quantity: item.quantity,

        purchasePrice: item.purchasePrice,

        tax: 0,

        total: item.total,
      })),

    subtotal: invoice.subtotal,

    taxAmount: invoice.taxAmount,

    discount: 0,

    grandTotal: invoice.grandTotal,

    notes: "Generated by OCR",
  };
}
